"""Evidence-triggered expert candidate proposal plane."""

from kapso.cross_run.contracts import (
    EMPTY_EXPERT_TREE_DIGEST,
    ExpertEvaluatorResultRecord,
)
from kapso.cross_run.expert.book import (
    EXPERT_BOOK_PATH,
    compile_expert_semantic_book,
    expert_semantic_book_digest,
)
from kapso.cross_run.expert.architect import ExpertRepositoryArchitect
from kapso.cross_run.expert.candidates import (
    ExpertCandidateClosure,
    ExpertCandidateValidationError,
    ExpertCandidateValidator,
)
from kapso.cross_run.expert.candidate_context import (
    ExpertCandidateContextError,
    ExpertCandidateReplayEvidence,
    ExpertCandidateValidationContext,
    compose_candidate_replay_evidence,
    project_agent_candidate_validation_context,
)
from kapso.cross_run.expert.candidate_derivations import (
    ExpertAgentProposalDerivation,
    ExpertAgentProposalDerivationRecord,
    ExpertCandidateDerivationError,
    ExpertCompositionSourceProvenance,
    ExpertDeterministicCompositionDerivation,
    ExpertDeterministicCompositionDerivationRecord,
)
from kapso.cross_run.expert.composition_contracts import (
    ExpertCompositionAssessment,
    ExpertCompositionBaseReference,
    ExpertCompositionConflict,
    ExpertCompositionConflictKind,
    ExpertCompositionConflictSubjectKind,
    ExpertCompositionContractError,
    ExpertCompositionDisposition,
    ExpertCompositionMaterialization,
    ExpertCompositionPlan,
    ExpertCompositionSourceReference,
)
from kapso.cross_run.expert.composition_base import (
    ExpertCompositionBaseClosure,
    ExpertCompositionBaseError,
    build_expert_composition_base_closure,
)
from kapso.cross_run.expert.composition_base_provider import (
    EXPERT_COMPOSITION_BASE_PROVIDER_VERSION,
    CurrentExpertCompositionBase,
    ExpertCompositionBaseProviderError,
    GitHubExpertCompositionBaseProvider,
)
from kapso.cross_run.expert.composition_source import (
    ApprovedExpertCompositionSource,
    ExpertCompositionSourceError,
    ExpertCompositionSourceResolver,
    project_expert_composition_source_reference,
)
from kapso.cross_run.expert.composition import (
    ExpertCompositionError,
    ExpertCompositionReducer,
    ExpertCompositionReduction,
    ExpertCompositionReductionSource,
)
from kapso.cross_run.expert.composition_candidate import (
    ExpertCompositionCandidateError,
    project_deterministic_composition_candidate,
)
from kapso.cross_run.expert.composition_admission_contracts import (
    ExpertCompositionAdmissionContractError,
    ExpertCompositionAdmissionFence,
    ExpertCompositionSourceAdmissionAuthority,
    composition_admission_security_subject_ids,
    validate_expert_composition_admission_fence,
)
from kapso.cross_run.expert.composition_admission import (
    ExpertCompositionAdmissionCoordinator,
    ExpertCompositionAdmissionDenylistAuthority,
    ExpertCompositionAdmissionError,
    build_expert_composition_plan,
    compose_expert_active_task_bindings,
)
from kapso.cross_run.expert.sanitation import ExpertCandidateSanitizer
from kapso.cross_run.expert.generalizer import ExpertCapabilityGeneralizer
from kapso.cross_run.expert.proposal import (
    ExpertCandidateProposalEngine,
    ExpertCandidateProposalResult,
)
from kapso.cross_run.expert.proposal_contract import (
    ExpertCandidateAncestorInput,
    ExpertProposalContractError,
)
from kapso.cross_run.expert.providers import GitHubExpertCurrentReleaseProvider
from kapso.cross_run.expert.replay_context import (
    SourceReplayContextProvider,
    VerifiedSourceReplayContext,
    VerifiedSourceReplayStartingArtifact,
)
from kapso.cross_run.expert.replay_request import (
    ExpertSourceReplayBundleProvider,
    ExpertSourceReplayCandidateReader,
    ExpertSourceReplayParentProvider,
    ExpertSourceReplayPreflightCoordinator,
    ExpertSourceReplayPreflightResult,
    ExpertSourceReplayRequestError,
    ExpertSourceReplayTaskAdapterProvider,
    ExpertSourceReplayValidationAuthority,
    MaterializedExpertSourceReplayCase,
    PreparedExpertSourceReplayRequest,
)
from kapso.cross_run.expert.task_evaluation_materialization import (
    TaskEvaluationMaterializationLimits,
    VerifiedTaskEvaluationAdapterRuntime,
    VerifiedTaskEvaluationCandidate,
    VerifiedTaskEvaluationParent,
    VerifiedTaskEvaluationStartingArtifact,
    materialize_task_evaluation_starting_artifacts,
)
from kapso.cross_run.expert.task_evaluation_contracts import (
    TaskEvaluationInvocationAllocation,
    TaskEvaluationRequest,
    TaskEvaluationReservation,
)
from kapso.cross_run.expert.task_evaluation_protocol import (
    build_task_evaluation_evaluator_request,
)
from kapso.cross_run.expert.task_evaluation_reservation import (
    ExpertTaskEvaluationReservationSnapshot,
)
from kapso.cross_run.expert.task_evaluation_execution import (
    ExecutableTaskEvaluationCase,
    ExecutableTaskEvaluationLeg,
    ResolvedTaskEvaluationCase,
    TaskEvaluationExecutionError,
    TaskEvaluationExecutionProvider,
    TaskEvaluationExecutionProviderKey,
    TaskEvaluationExecutionProviderRegistry,
    TaskEvaluationProviderCompletion,
    TaskEvaluationProviderExecutionHandle,
    TaskEvaluationProviderSupportRequirements,
    project_prepared_task_evaluation_cases,
    task_evaluation_provider_execution_handle,
)
from kapso.cross_run.expert.task_evaluation_execution_journal import (
    TASK_EVALUATION_EXECUTION_JOURNAL_SCHEMA_VERSION,
    TaskEvaluationExecutionJournalError,
    TaskEvaluationExecutionJournalEvent,
    TaskEvaluationExecutionJournalEventKind,
    TaskEvaluationExecutionPrefixState,
    TaskEvaluationProcessObservation,
    task_evaluation_execution_schedule,
    validate_task_evaluation_execution_prefix,
)
from kapso.cross_run.expert.task_evaluation_authority_contracts import (
    TaskEvaluationAuthorityError,
    TaskEvaluationCurrentReleaseObservation,
    TaskEvaluationSpawnAuthorityFence,
)
from kapso.cross_run.expert.task_evaluation_authority_projection import (
    build_task_evaluation_spawn_authority_fence,
    task_evaluation_adapter_trust_observations,
    task_evaluation_allocation_case_leg,
    task_evaluation_spawn_security_subject_ids,
)
from kapso.cross_run.expert.task_evaluation_preflight import (
    MaterializedTaskEvaluationCase,
    PreparedTaskEvaluationRequest,
    TaskEvaluationAdapterProvider,
    TaskEvaluationCandidateReader,
    TaskEvaluationCurrentReleaseAuthority,
    TaskEvaluationParentProvider,
    TaskEvaluationPlanReservationAuthority,
    TaskEvaluationPreflightCoordinator,
    TaskEvaluationPreflightError,
    task_evaluation_materialization_usage,
)
from kapso.cross_run.expert.replay_publication_contracts import (
    ExpertSourceReplayPublicationError,
    ExpertSourceReplayStageResultRecord,
    SourceReplayDecisionPublicationFence,
    source_replay_publication_security_subject_ids,
)
from kapso.cross_run.expert.replay_publication import (
    ExpertSourceReplayDecisionPublicationCoordinator,
    ExpertSourceReplayPublicationCurrentAuthority,
    ExpertSourceReplayPublicationDenylistAuthority,
)
from kapso.cross_run.expert.replay_stage import (
    ExpertSourceReplayPermanentlyInterruptedError,
    ExpertSourceReplayStageError,
    ExpertSourceReplayStageOrchestrator,
    SourceReplayProviderRegistryFactory,
)
from kapso.cross_run.expert.review import (
    ExpertAutomatedReviewCoordinator,
    ExpertAutomatedReviewExecution,
    PreparedExpertAutomatedReviewPacket,
)
from kapso.cross_run.expert.review_contracts import (
    EXPERT_AUTOMATED_REVIEW_CONTRACT_VERSION,
    ExpertAutomatedReviewAdjudication,
    ExpertAutomatedReviewAssertion,
    ExpertAutomatedReviewError,
    ExpertAutomatedReviewOperationRecord,
    ExpertAutomatedReviewOutcome,
    ExpertAutomatedReviewPacket,
    ExpertAutomatedReviewStageResultRecord,
)
from kapso.cross_run.expert.review_stage import (
    ExpertAutomatedReviewStageError,
    ExpertAutomatedReviewStageOrchestrator,
)
from kapso.cross_run.expert.promotion_stage import (
    ExpertReleaseMatrixStageCoordinator,
    ExpertReleaseMatrixStageError,
    ExpertReleaseMatrixStageExecution,
)
from kapso.cross_run.expert.promotion_stage_contracts import (
    ExpertReleaseMatrixStageContractError,
    ExpertReleaseMatrixStageResultRecord,
)
from kapso.cross_run.expert.promotion import (
    ExpertReleaseMatrixPromotionError,
    decide_expert_release_matrix_promotion,
)
from kapso.cross_run.expert.promotion_authority import (
    ExpertPublicationCurrentReleaseAuthority,
    ExpertPublicationEligibilityCoordinator,
    ExpertPublicationEligibilityError,
    ExpertPublicationEligibilityExecution,
    ExpertPublicationSecurityDenylistAuthority,
    build_publication_eligibility_stage_result,
    publication_eligibility_security_subject_ids,
    publication_eligibility_task_adapter_trust_observations,
)
from kapso.cross_run.expert.promotion_authority_contracts import (
    ExpertPublicationEligibilityAuthorityFence,
    ExpertPublicationEligibilityContractError,
    ExpertPublicationEligibilityStageResultRecord,
)
from kapso.cross_run.expert.promotion_decision_contracts import (
    ExpertReleaseMatrixDecisionError,
    ExpertReleaseMatrixDecisionOutcome,
    ExpertReleaseMatrixDecisionReason,
    ExpertReleaseMatrixPromotionDecision,
    ExpertReleaseMatrixReplicateAssessment,
    ExpertReleaseMatrixReplicateClassification,
)
from kapso.cross_run.expert.store import (
    ExpertCandidateStore,
    ExpertCandidateStoreError,
    StoredExpertCandidate,
    stored_candidate_admission_dependency_ids,
)
from kapso.cross_run.expert.triggers import (
    ExpertEvolutionTriggerDecision,
    ExpertParentTreeReceipt,
    ExpertTriggerDecisionStore,
    ExpertTriggerEvidencePacket,
    ExpertTriggerEvidencePacketBuilder,
    ExpertTriggerError,
    ExpertTriggerEvaluator,
    ExpertTriggerObservation,
    ExpertTriggerObservationKind,
)
from kapso.cross_run.expert.validation import (
    ExpertAttestationVerifier,
    ExpertCandidateEligibilityEvaluator,
    ExpertCurrentReleaseProvider,
    ExpertEligibilityResult,
    ExpertEvaluatorRunBuilder,
    ExpertValidationError,
    ExpertValidationAuthorityInvalidationResult,
    ExpertValidationPredecessor,
    ExpertValidationReducer,
    ExpertValidationStart,
    ExpertValidationStateProvider,
)
from kapso.cross_run.expert.validation_store import (
    ExpertAutomatedReviewStageCommitResult,
    ExpertPublicationEligibilityStageCommitResult,
    ExpertReleaseMatrixStageCommitResult,
    ExpertSourceReplayStageCommitResult,
    ExpertTaskEvaluationReservationCommitResult,
    ExpertValidationCommitResult,
    ExpertValidationCompareAndSwapError,
    ExpertValidationJournal,
    ExpertValidationStore,
    ExpertValidationStoreError,
)
from kapso.cross_run.expert.validation_operation_contracts import (
    ExpertValidationOperation,
    ExpertValidationOperationKind,
)
from kapso.cross_run.expert.validation_snapshots import (
    ExpertPublicationEligibilitySnapshot,
    ExpertReleaseMatrixPlanReservationSnapshot,
    ExpertReleaseMatrixSourceEvidenceSnapshot,
    ExpertValidationSnapshot,
    ExpertValidationTransition,
)
from kapso.cross_run.expert.workspace import (
    ExpertCandidateWorkspaceError,
    ExpertCandidateWorkspaceLease,
    ExpertCandidateWorkspaceManager,
    PreparedExpertCandidateWorkspace,
)
from kapso.cross_run.task_adapters import (
    VerifiedTaskAdapter,
    VerifiedTaskAdapterProvider,
)

__all__ = [
    "EXPERT_BOOK_PATH",
    "EXPERT_AUTOMATED_REVIEW_CONTRACT_VERSION",
    "EMPTY_EXPERT_TREE_DIGEST",
    "ExpertAutomatedReviewAdjudication",
    "ExpertAutomatedReviewAssertion",
    "ExpertAutomatedReviewCoordinator",
    "ExpertAutomatedReviewError",
    "ExpertAutomatedReviewExecution",
    "ExpertAutomatedReviewOperationRecord",
    "ExpertAutomatedReviewOutcome",
    "ExpertAutomatedReviewPacket",
    "ExpertAutomatedReviewStageResultRecord",
    "ExpertAutomatedReviewStageCommitResult",
    "ExpertAutomatedReviewStageError",
    "ExpertAutomatedReviewStageOrchestrator",
    "EXPERT_COMPOSITION_BASE_PROVIDER_VERSION",
    "ExpertEvolutionTriggerDecision",
    "GitHubExpertCurrentReleaseProvider",
    "GitHubExpertCompositionBaseProvider",
    "ExpertAttestationVerifier",
    "ExpertCandidateEligibilityEvaluator",
    "ExpertCurrentReleaseProvider",
    "ExpertCandidateClosure",
    "ExpertCandidateContextError",
    "ExpertCandidateDerivationError",
    "ExpertCandidateReplayEvidence",
    "ExpertCandidateValidationContext",
    "compose_candidate_replay_evidence",
    "ExpertAgentProposalDerivation",
    "ExpertAgentProposalDerivationRecord",
    "ExpertCompositionSourceProvenance",
    "ExpertDeterministicCompositionDerivation",
    "ExpertDeterministicCompositionDerivationRecord",
    "ExpertCandidateAncestorInput",
    "ExpertCandidateProposalEngine",
    "ExpertCandidateProposalResult",
    "ExpertCandidateValidationError",
    "ExpertCandidateValidator",
    "ExpertCompositionAssessment",
    "ExpertCompositionAdmissionContractError",
    "ExpertCompositionAdmissionCoordinator",
    "ExpertCompositionAdmissionDenylistAuthority",
    "ExpertCompositionAdmissionError",
    "ExpertCompositionAdmissionFence",
    "ExpertCompositionCandidateError",
    "ExpertCompositionBaseClosure",
    "ExpertCompositionBaseError",
    "ExpertCompositionBaseProviderError",
    "ExpertCompositionBaseReference",
    "ExpertCompositionConflict",
    "ExpertCompositionConflictKind",
    "ExpertCompositionConflictSubjectKind",
    "ExpertCompositionContractError",
    "ExpertCompositionDisposition",
    "ExpertCompositionError",
    "ExpertCompositionMaterialization",
    "ExpertCompositionPlan",
    "ExpertCompositionReducer",
    "ExpertCompositionReduction",
    "ExpertCompositionReductionSource",
    "ExpertCompositionSourceError",
    "ExpertCompositionSourceAdmissionAuthority",
    "ExpertCompositionSourceReference",
    "ExpertCompositionSourceResolver",
    "CurrentExpertCompositionBase",
    "ApprovedExpertCompositionSource",
    "ExpertCapabilityGeneralizer",
    "ExpertEligibilityResult",
    "ExpertEvaluatorRunBuilder",
    "ExpertEvaluatorResultRecord",
    "ExpertCandidateWorkspaceError",
    "ExpertCandidateWorkspaceLease",
    "ExpertCandidateWorkspaceManager",
    "ExpertCandidateSanitizer",
    "ExpertCandidateStore",
    "ExpertCandidateStoreError",
    "ExpertParentTreeReceipt",
    "ExpertPublicationCurrentReleaseAuthority",
    "ExpertPublicationEligibilityAuthorityFence",
    "ExpertPublicationEligibilityContractError",
    "ExpertPublicationEligibilityCoordinator",
    "ExpertPublicationEligibilityError",
    "ExpertPublicationEligibilityExecution",
    "ExpertPublicationEligibilitySnapshot",
    "ExpertPublicationEligibilityStageCommitResult",
    "ExpertPublicationEligibilityStageResultRecord",
    "ExpertPublicationSecurityDenylistAuthority",
    "ExpertProposalContractError",
    "ExpertRepositoryArchitect",
    "ExpertReleaseMatrixDecisionError",
    "ExpertReleaseMatrixDecisionOutcome",
    "ExpertReleaseMatrixDecisionReason",
    "ExpertReleaseMatrixPlanReservationSnapshot",
    "ExpertReleaseMatrixPromotionDecision",
    "ExpertReleaseMatrixPromotionError",
    "ExpertReleaseMatrixReplicateAssessment",
    "ExpertReleaseMatrixReplicateClassification",
    "ExpertReleaseMatrixSourceEvidenceSnapshot",
    "ExpertReleaseMatrixStageCommitResult",
    "ExpertReleaseMatrixStageContractError",
    "ExpertReleaseMatrixStageCoordinator",
    "ExpertReleaseMatrixStageError",
    "ExpertReleaseMatrixStageExecution",
    "ExpertReleaseMatrixStageResultRecord",
    "ExpertSourceReplayBundleProvider",
    "ExpertSourceReplayCandidateReader",
    "ExpertSourceReplayDecisionPublicationCoordinator",
    "ExpertSourceReplayParentProvider",
    "ExpertSourceReplayPreflightCoordinator",
    "ExpertSourceReplayPreflightResult",
    "ExpertSourceReplayPublicationError",
    "ExpertSourceReplayPublicationCurrentAuthority",
    "ExpertSourceReplayPublicationDenylistAuthority",
    "ExpertSourceReplayPermanentlyInterruptedError",
    "ExpertSourceReplayRequestError",
    "ExpertSourceReplayStageResultRecord",
    "ExpertSourceReplayStageCommitResult",
    "ExpertSourceReplayStageError",
    "ExpertSourceReplayStageOrchestrator",
    "ExpertSourceReplayTaskAdapterProvider",
    "ExpertSourceReplayValidationAuthority",
    "ExpertTriggerDecisionStore",
    "ExpertTriggerEvidencePacket",
    "ExpertTriggerEvidencePacketBuilder",
    "ExpertTriggerError",
    "ExpertTriggerEvaluator",
    "ExpertTriggerObservation",
    "ExpertTriggerObservationKind",
    "ExpertTaskEvaluationReservationCommitResult",
    "ExpertTaskEvaluationReservationSnapshot",
    "ExpertValidationError",
    "ExpertValidationAuthorityInvalidationResult",
    "ExpertValidationCommitResult",
    "ExpertValidationCompareAndSwapError",
    "ExpertValidationJournal",
    "ExpertValidationOperation",
    "ExpertValidationOperationKind",
    "ExpertValidationPredecessor",
    "ExpertValidationReducer",
    "ExpertValidationSnapshot",
    "ExpertValidationStart",
    "ExpertValidationStateProvider",
    "ExpertValidationStore",
    "ExpertValidationStoreError",
    "ExpertValidationTransition",
    "ExecutableTaskEvaluationCase",
    "ExecutableTaskEvaluationLeg",
    "VerifiedTaskAdapter",
    "VerifiedTaskAdapterProvider",
    "PreparedExpertCandidateWorkspace",
    "PreparedExpertAutomatedReviewPacket",
    "MaterializedExpertSourceReplayCase",
    "MaterializedTaskEvaluationCase",
    "PreparedExpertSourceReplayRequest",
    "PreparedTaskEvaluationRequest",
    "ResolvedTaskEvaluationCase",
    "SourceReplayContextProvider",
    "SourceReplayProviderRegistryFactory",
    "SourceReplayDecisionPublicationFence",
    "TaskEvaluationAdapterProvider",
    "TaskEvaluationAuthorityError",
    "TaskEvaluationCandidateReader",
    "TaskEvaluationCurrentReleaseAuthority",
    "TaskEvaluationCurrentReleaseObservation",
    "TaskEvaluationExecutionError",
    "TaskEvaluationExecutionJournalError",
    "TaskEvaluationExecutionJournalEvent",
    "TaskEvaluationExecutionJournalEventKind",
    "TaskEvaluationExecutionPrefixState",
    "TaskEvaluationExecutionProvider",
    "TaskEvaluationExecutionProviderKey",
    "TaskEvaluationExecutionProviderRegistry",
    "TaskEvaluationInvocationAllocation",
    "TaskEvaluationMaterializationLimits",
    "TaskEvaluationParentProvider",
    "TaskEvaluationPlanReservationAuthority",
    "TaskEvaluationPreflightCoordinator",
    "TaskEvaluationProcessObservation",
    "TaskEvaluationProviderCompletion",
    "TaskEvaluationProviderExecutionHandle",
    "TaskEvaluationProviderSupportRequirements",
    "TaskEvaluationRequest",
    "TaskEvaluationReservation",
    "TaskEvaluationSpawnAuthorityFence",
    "StoredExpertCandidate",
    "TaskEvaluationPreflightError",
    "VerifiedTaskEvaluationAdapterRuntime",
    "VerifiedTaskEvaluationCandidate",
    "VerifiedTaskEvaluationParent",
    "VerifiedTaskEvaluationStartingArtifact",
    "VerifiedSourceReplayContext",
    "VerifiedSourceReplayStartingArtifact",
    "build_expert_composition_base_closure",
    "build_expert_composition_plan",
    "compose_expert_active_task_bindings",
    "composition_admission_security_subject_ids",
    "materialize_task_evaluation_starting_artifacts",
    "publication_eligibility_security_subject_ids",
    "publication_eligibility_task_adapter_trust_observations",
    "project_expert_composition_source_reference",
    "project_agent_candidate_validation_context",
    "project_deterministic_composition_candidate",
    "project_prepared_task_evaluation_cases",
    "task_evaluation_adapter_trust_observations",
    "task_evaluation_allocation_case_leg",
    "task_evaluation_execution_schedule",
    "task_evaluation_materialization_usage",
    "task_evaluation_provider_execution_handle",
    "task_evaluation_spawn_security_subject_ids",
    "validate_task_evaluation_execution_prefix",
    "TASK_EVALUATION_EXECUTION_JOURNAL_SCHEMA_VERSION",
    "build_task_evaluation_evaluator_request",
    "build_task_evaluation_spawn_authority_fence",
    "build_publication_eligibility_stage_result",
    "compile_expert_semantic_book",
    "decide_expert_release_matrix_promotion",
    "expert_semantic_book_digest",
    "source_replay_publication_security_subject_ids",
    "stored_candidate_admission_dependency_ids",
    "validate_expert_composition_admission_fence",
]
