#!/bin/bash
# Setup nginx reverse proxy with SSL for Leeroopedia services
# Usage: ./setup.sh [--domain DOMAIN] [--email EMAIL]
#
# This script:
#   1. Installs nginx and certbot (if not already installed)
#   2. Creates nginx config for the domain
#   3. Obtains SSL certificate from Let's Encrypt
#   4. Sets up automatic certificate renewal
#
# Prerequisites:
#   - Domain DNS must point to this server's IP
#   - Ports 80 and 443 must be open in firewall/security group
#   - Wiki service must be running on port 8080
#   - Leeroopedia API must be running on port 8091

set -euo pipefail
cd "$(dirname "$0")"

# Default values
DOMAIN="${DOMAIN:-test-leeroopedia.leeroo.com}"
EMAIL="${EMAIL:-admin@leeroo.com}"
WIKI_PORT="${WIKI_PORT:-8090}"
API_PORT="${API_PORT:-8091}"

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --domain)
            DOMAIN="$2"
            shift 2
            ;;
        --email)
            EMAIL="$2"
            shift 2
            ;;
        --wiki-port)
            WIKI_PORT="$2"
            shift 2
            ;;
        --api-port)
            API_PORT="$2"
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            echo "Usage: ./setup.sh [--domain DOMAIN] [--email EMAIL] [--wiki-port PORT] [--api-port PORT]"
            exit 1
            ;;
    esac
done

echo "=========================================="
echo "  Nginx + SSL Setup"
echo "=========================================="
echo ""
echo "Domain:     $DOMAIN"
echo "Email:      $EMAIL"
echo "Wiki port:  $WIKI_PORT"
echo "API port:   $API_PORT"
echo ""

# Check if running as root or with sudo
if [[ $EUID -ne 0 ]]; then
    SUDO="sudo"
else
    SUDO=""
fi

# Install nginx and certbot if not present
echo "Checking dependencies..."
if ! command -v nginx &> /dev/null; then
    echo "Installing nginx..."
    $SUDO apt update
    $SUDO apt install -y nginx
fi

if ! command -v certbot &> /dev/null; then
    echo "Installing certbot..."
    $SUDO apt install -y certbot python3-certbot-nginx
fi

echo "✅ Dependencies installed"

# Create nginx config
echo ""
echo "Creating nginx configuration..."
NGINX_CONFIG="/etc/nginx/sites-available/$DOMAIN"

$SUDO tee "$NGINX_CONFIG" > /dev/null << EOF
# Nginx config for $DOMAIN
# Wiki at root, Leeroopedia API at /api
# Generated by setup.sh on $(date)

server {
    listen 80;
    server_name $DOMAIN;

    # Wiki at root
    location / {
        proxy_pass http://127.0.0.1:$WIKI_PORT;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        
        # WebSocket support (for VisualEditor, etc.)
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Increase timeouts for large uploads
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
        
        # Increase max body size for file uploads
        client_max_body_size 50M;
    }

    # Leeroopedia API at /api
    location /api/ {
        rewrite ^/api/(.*) /\$1 break;
        proxy_pass http://127.0.0.1:$API_PORT;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        
        proxy_http_version 1.1;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}
EOF

# Enable site
$SUDO ln -sf "$NGINX_CONFIG" /etc/nginx/sites-enabled/

# Test nginx config
echo "Testing nginx configuration..."
$SUDO nginx -t

# Reload nginx
$SUDO systemctl reload nginx
echo "✅ Nginx configured"

# Obtain SSL certificate
echo ""
echo "Obtaining SSL certificate..."
echo "   (This requires ports 80 and 443 to be accessible from the internet)"
echo ""

$SUDO certbot --nginx -d "$DOMAIN" \
    --non-interactive \
    --agree-tos \
    --email "$EMAIL" \
    --redirect

echo ""
echo "=========================================="
echo "  Setup Complete!"
echo "=========================================="
echo ""
echo "Your services are now available at:"
echo ""
echo "   Wiki:     https://$DOMAIN"
echo "   API:      https://$DOMAIN/api/"
echo "   API Docs: https://$DOMAIN/api/docs"
echo ""
echo "SSL certificate will auto-renew via certbot timer."
echo ""
echo "To check renewal status:"
echo "   sudo certbot certificates"
echo "   sudo systemctl list-timers | grep certbot"
echo ""
